/**
 * Brand logo lookup.
 * Each entry is a [substring, logoPath] pair. The substring is matched case-insensitively
 * against a brand name (airline, hotel name, vendor, event title, etc.).
 * First match wins, so put more-specific entries before less-specific ones.
 */
const CL = (domain: string) => `https://logo.clearbit.com/${domain}`;
// Google Flights airline logo CDN — indexed by IATA code, very reliable
const AIR = (iata: string) => `https://www.gstatic.com/flights/airline_logos/70px/${iata}.png`;

const LOGO_MAP: [string, string][] = [
  // ── Airlines (IATA codes via Google Flights CDN) ───────────────────────────
  ['american airlines',    AIR('AA')],
  ['american',             AIR('AA')],
  ['united airlines',      AIR('UA')],
  ['united',               AIR('UA')],
  ['delta',                AIR('DL')],
  ['southwest',            AIR('WN')],
  ['alaska airlines',      AIR('AS')],
  ['alaska',               AIR('AS')],
  ['jetblue',              AIR('B6')],
  ['spirit',               AIR('NK')],
  ['frontier',             AIR('F9')],
  ['allegiant',            AIR('G4')],
  ['hawaiian',             AIR('HA')],
  ['air canada',           AIR('AC')],
  ['british airways',      AIR('BA')],
  ['lufthansa',            AIR('LH')],
  ['air france',           AIR('AF')],
  ['emirates',             AIR('EK')],
  ['qatar',                AIR('QR')],
  ['klm',                  AIR('KL')],
  ['iberia',               AIR('IB')],
  ['swiss',                AIR('LX')],
  ['austrian',             AIR('OS')],
  ['tap air',              AIR('TP')],
  ['aer lingus',           AIR('EI')],
  ['ryanair',              AIR('FR')],
  ['easyjet',              AIR('U2')],
  ['wizz',                 AIR('W6')],
  ['vueling',              AIR('VY')],
  ['turkish',              AIR('TK')],
  ['etihad',               AIR('EY')],
  ['singapore',            AIR('SQ')],
  ['cathay',               AIR('CX')],
  ['ana ',                 AIR('NH')],
  ['japan airlines',       AIR('JL')],
  ['korean air',           AIR('KE')],
  ['air new zealand',      AIR('NZ')],
  ['qantas',               AIR('QF')],
  ['virgin australia',     AIR('VA')],
  ['virgin atlantic',      AIR('VS')],

  // ── Hotels ────────────────────────────────────────────────────────────────
  ['ritz-carlton',         CL('ritzcarlton.com')],
  ['ritz carlton',         CL('ritzcarlton.com')],
  ['four seasons',         CL('fourseasons.com')],
  ['st. regis',            CL('marriott.com')],
  ['w hotel',              CL('marriott.com')],
  ['westin',               CL('marriott.com')],
  ['sheraton',             CL('marriott.com')],
  ['le meridien',          CL('marriott.com')],
  ['autograph',            CL('marriott.com')],
  ['renaissance',          CL('marriott.com')],
  ['marriott',             CL('marriott.com')],
  ['courtyard',            CL('marriott.com')],
  ['fairfield',            CL('marriott.com')],
  ['springhill',           CL('marriott.com')],
  ['residence inn',        CL('marriott.com')],
  ['towneplace',           CL('marriott.com')],
  ['moxy',                 CL('marriott.com')],
  ['waldorf',              CL('hilton.com')],
  ['conrad',               CL('hilton.com')],
  ['curio',                CL('hilton.com')],
  ['doubletree',           CL('hilton.com')],
  ['embassy suites',       CL('hilton.com')],
  ['hilton garden',        CL('hilton.com')],
  ['hampton inn',          CL('hilton.com')],
  ['tru by hilton',        CL('hilton.com')],
  ['homewood',             CL('hilton.com')],
  ['home2',                CL('hilton.com')],
  ['tapestry',             CL('hilton.com')],
  ['hilton',               CL('hilton.com')],
  ['hyatt regency',        '/logos/hyatt.svg'],
  ['park hyatt',           '/logos/hyatt.svg'],
  ['grand hyatt',          '/logos/hyatt.svg'],
  ['andaz',                '/logos/hyatt.svg'],
  ['thompson',             '/logos/hyatt.svg'],
  ['alila',                '/logos/hyatt.svg'],
  ['hyatt',                '/logos/hyatt.svg'],
  ['intercontinental',     CL('ihg.com')],
  ['kimpton',              CL('ihg.com')],
  ['crowne plaza',         CL('ihg.com')],
  ['holiday inn',          CL('ihg.com')],
  ['even hotels',          CL('ihg.com')],
  ['indigo',               CL('ihg.com')],
  ['voco',                 CL('ihg.com')],
  ['ihg',                  CL('ihg.com')],
  ['wyndham',              CL('wyndhamhotels.com')],
  ['la quinta',            CL('wyndhamhotels.com')],
  ['ramada',               CL('wyndhamhotels.com')],
  ['days inn',             CL('wyndhamhotels.com')],
  ['super 8',              CL('wyndhamhotels.com')],
  ['microtel',             CL('wyndhamhotels.com')],
  ['hawthorn',             CL('wyndhamhotels.com')],
  ['best western',         CL('bestwestern.com')],
  ['radisson blu',         CL('radissonhotels.com')],
  ['radisson',             CL('radissonhotels.com')],
  ['omni',                 CL('omnihotels.com')],
  ['loews',                CL('loewshotels.com')],
  ['kimpton',              CL('kimptonhotels.com')],
  ['ace hotel',            CL('acehotel.com')],
  ['novotel',              CL('accor.com')],
  ['ibis',                 CL('accor.com')],
  ['sofitel',              CL('accor.com')],
  ['mercure',              CL('accor.com')],
  ['pullman',              CL('accor.com')],
  ['accor',                CL('accor.com')],
  ['mgm grand',            CL('mgmresorts.com')],
  ['bellagio',             CL('mgmresorts.com')],
  ['aria',                 CL('mgmresorts.com')],
  ['mgm',                  CL('mgmresorts.com')],
  ['caesars',              CL('caesars.com')],
  ['harrahs',              CL('caesars.com')],

  // ── Rental Cars ───────────────────────────────────────────────────────────
  ['enterprise',           '/logos/enterprise.svg'],
  ['national car',         CL('nationalcar.com')],
  ['national',             CL('nationalcar.com')],
  ['alamo',                CL('alamo.com')],
  ['hertz',                CL('hertz.com')],
  ['avis',                 CL('avis.com')],
  ['budget',               CL('budget.com')],
  ['dollar',               CL('dollar.com')],
  ['thrifty',              CL('thrifty.com')],
  ['sixt',                 CL('sixt.com')],
  ['payless',              CL('paylesscar.com')],
  ['fox rent',             CL('foxrentacar.com')],
  ['turo',                 CL('turo.com')],
  ['zipcar',               CL('zipcar.com')],

  // ── Ticket vendors ────────────────────────────────────────────────────────
  ['ticketmaster',         '/logos/ticketmaster.svg'],
  ['stubhub',              '/logos/stubhub.svg'],
  ['seatgeek',             CL('seatgeek.com')],
  ['vivid seats',          CL('vividseats.com')],
  ['axs',                  CL('axs.com')],

  // ── Venues & events ───────────────────────────────────────────────────────
  ['georgia aquarium',     '/logos/aquarium.svg'],
  ['aquarium',             '/logos/aquarium.svg'],
  ['atlanta braves',       '/logos/braves.svg'],
  ['truist park',          '/logos/braves.svg'],
  ['braves',               '/logos/braves.svg'],
  ['world cup',            '/logos/fifa2026.png'],
  ['fifa',                 '/logos/fifa2026.png'],

  // ── MLB ───────────────────────────────────────────────────────────────────
  ['arizona diamondbacks',  '/logos/mlb-ari.png'],
  ['diamondbacks',          '/logos/mlb-ari.png'],
  ['chase field',           '/logos/mlb-ari.png'],
  ['baltimore orioles',     '/logos/mlb-bal.png'],
  ['orioles',               '/logos/mlb-bal.png'],
  ['boston red sox',        '/logos/mlb-bos.png'],
  ['red sox',               '/logos/mlb-bos.png'],
  ['fenway park',           '/logos/mlb-bos.png'],
  ['chicago cubs',          '/logos/mlb-chc.png'],
  ['cubs',                  '/logos/mlb-chc.png'],
  ['wrigley field',         '/logos/mlb-chc.png'],
  ['chicago white sox',     '/logos/mlb-chw.png'],
  ['white sox',             '/logos/mlb-chw.png'],
  ['cincinnati reds',       '/logos/mlb-cin.png'],
  ['reds',                  '/logos/mlb-cin.png'],
  ['cleveland guardians',   '/logos/mlb-cle.png'],
  ['guardians',             '/logos/mlb-cle.png'],
  ['colorado rockies',      '/logos/mlb-col.png'],
  ['rockies',               '/logos/mlb-col.png'],
  ['coors field',           '/logos/mlb-col.png'],
  ['detroit tigers',        '/logos/mlb-det.png'],
  ['tigers',                '/logos/mlb-det.png'],
  ['houston astros',        '/logos/mlb-hou.png'],
  ['astros',                '/logos/mlb-hou.png'],
  ['minute maid park',      '/logos/mlb-hou.png'],
  ['kansas city royals',    '/logos/mlb-kc.png'],
  ['royals',                '/logos/mlb-kc.png'],
  ['los angeles angels',    '/logos/mlb-laa.png'],
  ['la angels',             '/logos/mlb-laa.png'],
  ['angels',                '/logos/mlb-laa.png'],
  ['los angeles dodgers',   '/logos/mlb-lad.png'],
  ['la dodgers',            '/logos/mlb-lad.png'],
  ['dodgers',               '/logos/mlb-lad.png'],
  ['dodger stadium',        '/logos/mlb-lad.png'],
  ['miami marlins',         '/logos/mlb-mia.png'],
  ['marlins',               '/logos/mlb-mia.png'],
  ['milwaukee brewers',     '/logos/mlb-mil.png'],
  ['brewers',               '/logos/mlb-mil.png'],
  ['minnesota twins',       '/logos/mlb-min.png'],
  ['twins',                 '/logos/mlb-min.png'],
  ['new york mets',         '/logos/mlb-nym.png'],
  ['ny mets',               '/logos/mlb-nym.png'],
  ['mets',                  '/logos/mlb-nym.png'],
  ['citi field',            '/logos/mlb-nym.png'],
  ['new york yankees',      '/logos/mlb-nyy.png'],
  ['ny yankees',            '/logos/mlb-nyy.png'],
  ['yankees',               '/logos/mlb-nyy.png'],
  ['yankee stadium',        '/logos/mlb-nyy.png'],
  ['oakland athletics',     '/logos/mlb-oak.png'],
  ['athletics',             '/logos/mlb-oak.png'],
  ['philadelphia phillies', '/logos/mlb-phi.png'],
  ['phillies',              '/logos/mlb-phi.png'],
  ['pittsburgh pirates',    '/logos/mlb-pit.png'],
  ['pirates',               '/logos/mlb-pit.png'],
  ['pnc park',              '/logos/mlb-pit.png'],
  ['san diego padres',      '/logos/mlb-sd.png'],
  ['padres',                '/logos/mlb-sd.png'],
  ['petco park',            '/logos/mlb-sd.png'],
  ['seattle mariners',      '/logos/mlb-sea.png'],
  ['mariners',              '/logos/mlb-sea.png'],
  ['san francisco giants',  '/logos/mlb-sf.png'],
  ['sf giants',             '/logos/mlb-sf.png'],
  ['oracle park',           '/logos/mlb-sf.png'],
  ['st. louis cardinals',   '/logos/mlb-stl.png'],
  ['busch stadium',         '/logos/mlb-stl.png'],
  ['tampa bay rays',        '/logos/mlb-tb.png'],
  ['rays',                  '/logos/mlb-tb.png'],
  ['texas rangers',         '/logos/mlb-tex.png'],
  ['globe life field',      '/logos/mlb-tex.png'],
  ['toronto blue jays',     '/logos/mlb-tor.png'],
  ['blue jays',             '/logos/mlb-tor.png'],
  ['washington nationals',  '/logos/mlb-wsh.png'],
  ['nationals',             '/logos/mlb-wsh.png'],
  ['nationals park',        '/logos/mlb-wsh.png'],

  // ── NFL ───────────────────────────────────────────────────────────────────
  ['arizona cardinals',     '/logos/nfl-ari.png'],
  ['atlanta falcons',       '/logos/nfl-atl.png'],
  ['falcons',               '/logos/nfl-atl.png'],
  ['baltimore ravens',      '/logos/nfl-bal.png'],
  ['ravens',                '/logos/nfl-bal.png'],
  ['buffalo bills',         '/logos/nfl-buf.png'],
  ['bills',                 '/logos/nfl-buf.png'],
  ['carolina panthers',     '/logos/nfl-car.png'],
  ['chicago bears',         '/logos/nfl-chi.png'],
  ['bears',                 '/logos/nfl-chi.png'],
  ['soldier field',         '/logos/nfl-chi.png'],
  ['cincinnati bengals',    '/logos/nfl-cin.png'],
  ['bengals',               '/logos/nfl-cin.png'],
  ['cleveland browns',      '/logos/nfl-cle.png'],
  ['browns',                '/logos/nfl-cle.png'],
  ['dallas cowboys',        '/logos/nfl-dal.png'],
  ['cowboys',               '/logos/nfl-dal.png'],
  ['denver broncos',        '/logos/nfl-den.png'],
  ['broncos',               '/logos/nfl-den.png'],
  ['detroit lions',         '/logos/nfl-det.png'],
  ['lions',                 '/logos/nfl-det.png'],
  ['ford field',            '/logos/nfl-det.png'],
  ['green bay packers',     '/logos/nfl-gb.png'],
  ['packers',               '/logos/nfl-gb.png'],
  ['lambeau field',         '/logos/nfl-gb.png'],
  ['houston texans',        '/logos/nfl-hou.png'],
  ['texans',                '/logos/nfl-hou.png'],
  ['indianapolis colts',    '/logos/nfl-ind.png'],
  ['colts',                 '/logos/nfl-ind.png'],
  ['jacksonville jaguars',  '/logos/nfl-jax.png'],
  ['jaguars',               '/logos/nfl-jax.png'],
  ['kansas city chiefs',    '/logos/nfl-kc.png'],
  ['chiefs',                '/logos/nfl-kc.png'],
  ['los angeles chargers',  '/logos/nfl-lac.png'],
  ['la chargers',           '/logos/nfl-lac.png'],
  ['chargers',              '/logos/nfl-lac.png'],
  ['los angeles rams',      '/logos/nfl-lar.png'],
  ['la rams',               '/logos/nfl-lar.png'],
  ['rams',                  '/logos/nfl-lar.png'],
  ['las vegas raiders',     '/logos/nfl-lv.png'],
  ['raiders',               '/logos/nfl-lv.png'],
  ['miami dolphins',        '/logos/nfl-mia.png'],
  ['dolphins',              '/logos/nfl-mia.png'],
  ['minnesota vikings',     '/logos/nfl-min.png'],
  ['vikings',               '/logos/nfl-min.png'],
  ['new england patriots',  '/logos/nfl-ne.png'],
  ['patriots',              '/logos/nfl-ne.png'],
  ['gillette stadium',      '/logos/nfl-ne.png'],
  ['new orleans saints',    '/logos/nfl-no.png'],
  ['saints',                '/logos/nfl-no.png'],
  ['new york giants',       '/logos/nfl-nyg.png'],
  ['ny giants',             '/logos/nfl-nyg.png'],
  ['new york jets',         '/logos/nfl-nyj.png'],
  ['ny jets',               '/logos/nfl-nyj.png'],
  ['philadelphia eagles',   '/logos/nfl-phi.png'],
  ['eagles',                '/logos/nfl-phi.png'],
  ['pittsburgh steelers',   '/logos/nfl-pit.png'],
  ['steelers',              '/logos/nfl-pit.png'],
  ['seattle seahawks',      '/logos/nfl-sea.png'],
  ['seahawks',              '/logos/nfl-sea.png'],
  ['lumen field',           '/logos/nfl-sea.png'],
  ['san francisco 49ers',   '/logos/nfl-sf.png'],
  ['49ers',                 '/logos/nfl-sf.png'],
  ['niners',                '/logos/nfl-sf.png'],
  ['tampa bay buccaneers',  '/logos/nfl-tb.png'],
  ['buccaneers',            '/logos/nfl-tb.png'],
  ['bucs',                  '/logos/nfl-tb.png'],
  ['tennessee titans',      '/logos/nfl-ten.png'],
  ['titans',                '/logos/nfl-ten.png'],
  ['washington commanders', '/logos/nfl-wsh.png'],
  ['commanders',            '/logos/nfl-wsh.png'],

  // ── NHL (blackhawks before hawks to avoid substring collision) ─────────────
  ['chicago blackhawks',    '/logos/nhl-chi.png'],
  ['blackhawks',            '/logos/nhl-chi.png'],
  ['anaheim ducks',         '/logos/nhl-ana.png'],
  ['ducks',                 '/logos/nhl-ana.png'],
  ['honda center',          '/logos/nhl-ana.png'],
  ['boston bruins',         '/logos/nhl-bos.png'],
  ['bruins',                '/logos/nhl-bos.png'],
  ['buffalo sabres',        '/logos/nhl-buf.png'],
  ['sabres',                '/logos/nhl-buf.png'],
  ['carolina hurricanes',   '/logos/nhl-car.png'],
  ['hurricanes',            '/logos/nhl-car.png'],
  ['pnc arena',             '/logos/nhl-car.png'],
  ['columbus blue jackets', '/logos/nhl-cbj.png'],
  ['blue jackets',          '/logos/nhl-cbj.png'],
  ['calgary flames',        '/logos/nhl-cgy.png'],
  ['flames',                '/logos/nhl-cgy.png'],
  ['colorado avalanche',    '/logos/nhl-col.png'],
  ['avalanche',             '/logos/nhl-col.png'],
  ['avs',                   '/logos/nhl-col.png'],
  ['dallas stars',          '/logos/nhl-dal.png'],
  ['stars',                 '/logos/nhl-dal.png'],
  ['detroit red wings',     '/logos/nhl-det.png'],
  ['red wings',             '/logos/nhl-det.png'],
  ['edmonton oilers',       '/logos/nhl-edm.png'],
  ['oilers',                '/logos/nhl-edm.png'],
  ['rogers place',          '/logos/nhl-edm.png'],
  ['florida panthers',      '/logos/nhl-fla.png'],
  ['amerant bank arena',    '/logos/nhl-fla.png'],
  ['minnesota wild',        '/logos/nhl-min.png'],
  ['montreal canadiens',    '/logos/nhl-mtl.png'],
  ['canadiens',             '/logos/nhl-mtl.png'],
  ['habs',                  '/logos/nhl-mtl.png'],
  ['bell centre',           '/logos/nhl-mtl.png'],
  ['new jersey devils',     '/logos/nhl-njd.png'],
  ['devils',                '/logos/nhl-njd.png'],
  ['prudential center',     '/logos/nhl-njd.png'],
  ['nashville predators',   '/logos/nhl-nsh.png'],
  ['predators',             '/logos/nhl-nsh.png'],
  ['preds',                 '/logos/nhl-nsh.png'],
  ['bridgestone arena',     '/logos/nhl-nsh.png'],
  ['new york islanders',    '/logos/nhl-nyi.png'],
  ['islanders',             '/logos/nhl-nyi.png'],
  ['ubs arena',             '/logos/nhl-nyi.png'],
  ['new york rangers',      '/logos/nhl-nyr.png'],
  ['rangers',               '/logos/nhl-nyr.png'],
  ['ottawa senators',       '/logos/nhl-ott.png'],
  ['senators',              '/logos/nhl-ott.png'],
  ['philadelphia flyers',   '/logos/nhl-phi.png'],
  ['flyers',                '/logos/nhl-phi.png'],
  ['pittsburgh penguins',   '/logos/nhl-pit.png'],
  ['penguins',              '/logos/nhl-pit.png'],
  ['pens',                  '/logos/nhl-pit.png'],
  ['ppg paints arena',      '/logos/nhl-pit.png'],
  ['seattle kraken',        '/logos/nhl-sea.png'],
  ['kraken',                '/logos/nhl-sea.png'],
  ['climate pledge arena',  '/logos/nhl-sea.png'],
  ['st. louis blues',       '/logos/nhl-stl.png'],
  ['tampa bay lightning',   '/logos/nhl-tb.png'],
  ['lightning',             '/logos/nhl-tb.png'],
  ['bolts',                 '/logos/nhl-tb.png'],
  ['amalie arena',          '/logos/nhl-tb.png'],
  ['toronto maple leafs',   '/logos/nhl-tor.png'],
  ['maple leafs',           '/logos/nhl-tor.png'],
  ['leafs',                 '/logos/nhl-tor.png'],
  ['utah hockey club',      '/logos/nhl-utah.png'],
  ['utah hc',               '/logos/nhl-utah.png'],
  ['vancouver canucks',     '/logos/nhl-van.png'],
  ['canucks',               '/logos/nhl-van.png'],
  ['rogers arena',          '/logos/nhl-van.png'],
  ['vegas golden knights',  '/logos/nhl-vgk.png'],
  ['golden knights',        '/logos/nhl-vgk.png'],
  ['t-mobile arena',        '/logos/nhl-vgk.png'],
  ['winnipeg jets',         '/logos/nhl-wpg.png'],
  ['canada life centre',    '/logos/nhl-wpg.png'],
  ['washington capitals',   '/logos/nhl-wsh.png'],
  ['capitals',              '/logos/nhl-wsh.png'],
  ['caps',                  '/logos/nhl-wsh.png'],

  // ── NBA ───────────────────────────────────────────────────────────────────
  ['atlanta hawks',         '/logos/nba-atl.png'],
  ['state farm arena',      '/logos/nba-atl.png'],
  ['brooklyn nets',         '/logos/nba-bkn.png'],
  ['nets',                  '/logos/nba-bkn.png'],
  ['barclays center',       '/logos/nba-bkn.png'],
  ['boston celtics',        '/logos/nba-bos.png'],
  ['celtics',               '/logos/nba-bos.png'],
  ['td garden',             '/logos/nba-bos.png'],
  ['charlotte hornets',     '/logos/nba-cha.png'],
  ['hornets',               '/logos/nba-cha.png'],
  ['chicago bulls',         '/logos/nba-chi.png'],
  ['bulls',                 '/logos/nba-chi.png'],
  ['cleveland cavaliers',   '/logos/nba-cle.png'],
  ['cavaliers',             '/logos/nba-cle.png'],
  ['cavs',                  '/logos/nba-cle.png'],
  ['dallas mavericks',      '/logos/nba-dal.png'],
  ['mavericks',             '/logos/nba-dal.png'],
  ['mavs',                  '/logos/nba-dal.png'],
  ['denver nuggets',        '/logos/nba-den.png'],
  ['nuggets',               '/logos/nba-den.png'],
  ['ball arena',            '/logos/nba-den.png'],
  ['detroit pistons',       '/logos/nba-det.png'],
  ['pistons',               '/logos/nba-det.png'],
  ['golden state warriors', '/logos/nba-gs.png'],
  ['warriors',              '/logos/nba-gs.png'],
  ['chase center',          '/logos/nba-gs.png'],
  ['houston rockets',       '/logos/nba-hou.png'],
  ['rockets',               '/logos/nba-hou.png'],
  ['toyota center',         '/logos/nba-hou.png'],
  ['indiana pacers',        '/logos/nba-ind.png'],
  ['pacers',                '/logos/nba-ind.png'],
  ['la clippers',           '/logos/nba-lac.png'],
  ['clippers',              '/logos/nba-lac.png'],
  ['intuit dome',           '/logos/nba-lac.png'],
  ['los angeles lakers',    '/logos/nba-lal.png'],
  ['la lakers',             '/logos/nba-lal.png'],
  ['lakers',                '/logos/nba-lal.png'],
  ['memphis grizzlies',     '/logos/nba-mem.png'],
  ['grizzlies',             '/logos/nba-mem.png'],
  ['miami heat',            '/logos/nba-mia.png'],
  ['heat',                  '/logos/nba-mia.png'],
  ['kaseya center',         '/logos/nba-mia.png'],
  ['milwaukee bucks',       '/logos/nba-mil.png'],
  ['bucks',                 '/logos/nba-mil.png'],
  ['fiserv forum',          '/logos/nba-mil.png'],
  ['minnesota timberwolves','/logos/nba-min.png'],
  ['timberwolves',          '/logos/nba-min.png'],
  ['new orleans pelicans',  '/logos/nba-no.png'],
  ['pelicans',              '/logos/nba-no.png'],
  ['new york knicks',       '/logos/nba-ny.png'],
  ['ny knicks',             '/logos/nba-ny.png'],
  ['knicks',                '/logos/nba-ny.png'],
  ['madison square garden', '/logos/nba-ny.png'],
  ['oklahoma city thunder', '/logos/nba-okc.png'],
  ['okc thunder',           '/logos/nba-okc.png'],
  ['thunder',               '/logos/nba-okc.png'],
  ['orlando magic',         '/logos/nba-orl.png'],
  ['philadelphia 76ers',    '/logos/nba-phi.png'],
  ['76ers',                 '/logos/nba-phi.png'],
  ['sixers',                '/logos/nba-phi.png'],
  ['phoenix suns',          '/logos/nba-phx.png'],
  ['suns',                  '/logos/nba-phx.png'],
  ['portland trail blazers','/logos/nba-por.png'],
  ['trail blazers',         '/logos/nba-por.png'],
  ['blazers',               '/logos/nba-por.png'],
  ['san antonio spurs',     '/logos/nba-sa.png'],
  ['spurs',                 '/logos/nba-sa.png'],
  ['sacramento kings',      '/logos/nba-sac.png'],
  ['kings',                 '/logos/nba-sac.png'],
  ['toronto raptors',       '/logos/nba-tor.png'],
  ['raptors',               '/logos/nba-tor.png'],
  ['scotiabank arena',      '/logos/nba-tor.png'],
  ['utah jazz',             '/logos/nba-utah.png'],
  ['jazz',                  '/logos/nba-utah.png'],
  ['washington wizards',    '/logos/nba-wsh.png'],
  ['wizards',               '/logos/nba-wsh.png'],
  ['capital one arena',     '/logos/nba-wsh.png'],
];

/**
 * Returns a /logos/... path when a known brand is found within `name`, otherwise null.
 */
export function getLogoPath(name: string | null | undefined): string | null {
  if (!name) return null;
  const lower = name.toLowerCase();
  for (const [key, path] of LOGO_MAP) {
    if (lower.includes(key)) return path;
  }
  return null;
}

/**
 * Tries each name in order and returns the first logo path found, or null.
 * Useful when you want to fall back from vendor → title etc.
 */
export function getLogoPathFromAny(...names: (string | null | undefined)[]): string | null {
  for (const name of names) {
    const p = getLogoPath(name);
    if (p) return p;
  }
  return null;
}
